export const imageManifest: Record<string, string[]> = {
  "/images/art/dance/ailey": ["/images/art/dance/ailey-1.webp","/images/art/dance/ailey-2.jpg"],
  "/images/art/dance/allen": ["/images/art/dance/allen-1.jpeg","/images/art/dance/allen-2.jpg"],
  "/images/art/dance/copeland": ["/images/art/dance/copeland-1.jpg","/images/art/dance/copeland-2.jpg"],
  "/images/art/dance/dunham": ["/images/art/dance/dunham-1.jpeg","/images/art/dance/dunham-2.webp"],
  "/images/art/film/coogler": ["/images/art/film/coogler-1.jpg","/images/art/film/coogler-2.png"],
  "/images/art/film/duvernay": ["/images/art/film/duvernay-1.jpg","/images/art/film/duvernay-2.jpeg"],
  "/images/art/film/lee": ["/images/art/film/lee-1.webp","/images/art/film/lee-2.jpg"],
  "/images/art/film/peele": ["/images/art/film/peele-1.webp","/images/art/film/peele-2.webp"],
  "/images/art/music/armstrong": ["/images/art/music/armstrong-1.jpeg","/images/art/music/armstrong-2.png"],
  "/images/art/music/franklin": ["/images/art/music/franklin-1.jpg","/images/art/music/franklin-2.webp"],
  "/images/art/music/lamar": ["/images/art/music/lamar-1.jpeg","/images/art/music/lamar-2.webp"],
  "/images/art/music/simone": ["/images/art/music/simone-1.jpeg","/images/art/music/simone-2.jpg"],
  "/images/art/visual/basquiat": ["/images/art/visual/basquiat-1.jpeg","/images/art/visual/basquiat-2.jpg"],
  "/images/art/visual/ringgold": ["/images/art/visual/ringgold-1.jpeg","/images/art/visual/ringgold-2.jpeg"],
  "/images/art/visual/walker": ["/images/art/visual/walker-1.jpg","/images/art/visual/walker-2.jpeg"],
  "/images/art/visual/wiley": ["/images/art/visual/wiley-1.jpg","/images/art/visual/wiley-2.jpeg"],
  "/images/history/african diaspora/achebe": ["/images/history/african diaspora/achebe-1.webp","/images/history/african diaspora/achebe-2.jpeg"],
  "/images/history/african diaspora/dubois": ["/images/history/african diaspora/dubois-1.webp","/images/history/african diaspora/dubois-2.jpg"],
  "/images/history/african diaspora/fanon": ["/images/history/african diaspora/fanon-1.jpeg","/images/history/african diaspora/fanon-2.webp"],
  "/images/history/african diaspora/garvey": ["/images/history/african diaspora/garvey-1.jpg","/images/history/african diaspora/garvey-2.jpg"],
  "/images/history/civil rights/colvin": ["/images/history/civil rights/colvin-1.jpg","/images/history/civil rights/colvin-2.jpg"],
  "/images/history/civil rights/hamer": ["/images/history/civil rights/hamer-1.webp","/images/history/civil rights/hamer-2.jpg"],
  "/images/history/civil rights/king": ["/images/history/civil rights/king-1.webp","/images/history/civil rights/king-2.jpg"],
  "/images/history/civil rights/x": ["/images/history/civil rights/x-1.webp","/images/history/civil rights/x-2.webp"],
  "/images/history/culture/gates": ["/images/history/culture/gates-1.jpg","/images/history/culture/gates-2.jpg"],
  "/images/history/culture/hine": ["/images/history/culture/hine-1.jpg","/images/history/culture/hine-2.jpg"],
  "/images/history/culture/painter": ["/images/history/culture/painter-1.webp","/images/history/culture/painter-2.jpg"],
  "/images/history/culture/woodson": ["/images/history/culture/woodson-1.jpg","/images/history/culture/woodson-2.webp"],
  "/images/history/politics/b-jordan": ["/images/history/politics/b-jordan-1.webp","/images/history/politics/b-jordan-2.jpeg"],
  "/images/history/politics/chisholm": ["/images/history/politics/chisholm-1.jpeg","/images/history/politics/chisholm-2.jpeg"],
  "/images/history/politics/lewis": ["/images/history/politics/lewis-1.webp","/images/history/politics/lewis-2.jpeg"],
  "/images/history/politics/marshall": ["/images/history/politics/marshall-1.jpeg","/images/history/politics/marshall-2.jpg"],
  "/images/literature/essays/baldwin": ["/images/literature/essays/baldwin-1.jpg","/images/literature/essays/baldwin-2.jpg"],
  "/images/literature/essays/coates": ["/images/literature/essays/coates-1.webp","/images/literature/essays/coates-2.jpg"],
  "/images/literature/essays/ellison": ["/images/literature/essays/ellison-1.webp","/images/literature/essays/ellison-2.jpg"],
  "/images/literature/essays/hooks": ["/images/literature/essays/hooks-1.jpeg","/images/literature/essays/hooks-2.webp"],
  "/images/literature/fiction/butler": ["/images/literature/fiction/butler-1.jpeg","/images/literature/fiction/butler-2.webp"],
  "/images/literature/fiction/hurston": ["/images/literature/fiction/hurston-1.jpeg","/images/literature/fiction/hurston-2.jpg"],
  "/images/literature/fiction/morrison": ["/images/literature/fiction/morrison-1.jpg","/images/literature/fiction/morrison-2.jpg"],
  "/images/literature/fiction/whitehead": ["/images/literature/fiction/whitehead-1.jpg","/images/literature/fiction/whitehead-2.jpg"],
  "/images/literature/journalism/cobb": ["/images/literature/journalism/cobb-1.jpeg","/images/literature/journalism/cobb-2.jpeg"],
  "/images/literature/journalism/gault": ["/images/literature/journalism/gault-1.jpg","/images/literature/journalism/gault-2.jpg"],
  "/images/literature/journalism/jones": ["/images/literature/journalism/jones-1.jpg","/images/literature/journalism/jones-2.png"],
  "/images/literature/journalism/wells": ["/images/literature/journalism/wells-1.webp","/images/literature/journalism/wells-2.jpg"],
  "/images/literature/poetry/angelou": ["/images/literature/poetry/angelou-1.jpg","/images/literature/poetry/angelou-2.webp"],
  "/images/literature/poetry/brooks": ["/images/literature/poetry/brooks-1.jpg","/images/literature/poetry/brooks-2.jpeg"],
  "/images/literature/poetry/gorman": ["/images/literature/poetry/gorman-1.jpeg","/images/literature/poetry/gorman-2.webp"],
  "/images/literature/poetry/hughes": ["/images/literature/poetry/hughes-1.jpg","/images/literature/poetry/hughes-2.jpg"],
  "/images/mathematics/algebra/falconer": ["/images/mathematics/algebra/falconer-1.jpg","/images/mathematics/algebra/falconer-2.jpg"],
  "/images/mathematics/algebra/miller": ["/images/mathematics/algebra/miller-1.jpeg","/images/mathematics/algebra/miller-2.jpeg"],
  "/images/mathematics/algebra/stephens": ["/images/mathematics/algebra/stephens-1.png","/images/mathematics/algebra/stephens-2.jpg"],
  "/images/mathematics/algebra/woodard": ["/images/mathematics/algebra/woodard-1.jpg","/images/mathematics/algebra/woodard-2.jpeg"],
  "/images/mathematics/applied mathematics/granville": ["/images/mathematics/applied mathematics/granville-1.jpg","/images/mathematics/applied mathematics/granville-2.jpeg"],
  "/images/mathematics/applied mathematics/k-johnson": ["/images/mathematics/applied mathematics/k-johnson-1.webp","/images/mathematics/applied mathematics/k-johnson-2.jpeg"],
  "/images/mathematics/applied mathematics/petters": ["/images/mathematics/applied mathematics/petters-1.jpg","/images/mathematics/applied mathematics/petters-2.jpg"],
  "/images/mathematics/applied mathematics/vaughan": ["/images/mathematics/applied mathematics/vaughan-1.jpg","/images/mathematics/applied mathematics/vaughan-2.jpg"],
  "/images/mathematics/calculus/claytor": ["/images/mathematics/calculus/claytor-1.jpeg","/images/mathematics/calculus/claytor-2.jpeg"],
  "/images/mathematics/calculus/darden": ["/images/mathematics/calculus/darden-1.jpg","/images/mathematics/calculus/darden-2.jpg"],
  "/images/mathematics/calculus/easley": ["/images/mathematics/calculus/easley-1.jpeg","/images/mathematics/calculus/easley-2.jpg"],
  "/images/mathematics/calculus/west": ["/images/mathematics/calculus/west-1.jpg","/images/mathematics/calculus/west-2.webp"],
  "/images/mathematics/statistics & probability/blackwell": ["/images/mathematics/statistics & probability/blackwell-1.jpg","/images/mathematics/statistics & probability/blackwell-2.jpeg"],
  "/images/mathematics/statistics & probability/goins": ["/images/mathematics/statistics & probability/goins-1.jpeg","/images/mathematics/statistics & probability/goins-2.jpeg"],
  "/images/mathematics/statistics & probability/reid": ["/images/mathematics/statistics & probability/reid-1.jpeg","/images/mathematics/statistics & probability/reid-2.webp"],
  "/images/mathematics/statistics & probability/williams": ["/images/mathematics/statistics & probability/williams-1.png","/images/mathematics/statistics & probability/williams-2.jpg"],
  "/images/sciences/biology/canady": ["/images/sciences/biology/canady-1.jpeg","/images/sciences/biology/canady-2.jpg"],
  "/images/sciences/biology/drew": ["/images/sciences/biology/drew-1.jpg","/images/sciences/biology/drew-2.jpg"],
  "/images/sciences/biology/just": ["/images/sciences/biology/just-1.jpg","/images/sciences/biology/just-2.jpg"],
  "/images/sciences/biology/wright": ["/images/sciences/biology/wright-1.png","/images/sciences/biology/wright-2.jpeg"],
  "/images/sciences/chemistry/ball": ["/images/sciences/chemistry/ball-1.jpg","/images/sciences/chemistry/ball-2.jpg"],
  "/images/sciences/chemistry/brady": ["/images/sciences/chemistry/brady-1.jpeg","/images/sciences/chemistry/brady-2.jpg"],
  "/images/sciences/chemistry/ferguson": ["/images/sciences/chemistry/ferguson-1.jpg","/images/sciences/chemistry/ferguson-2.jpeg"],
  "/images/sciences/chemistry/julian": ["/images/sciences/chemistry/julian-1.jpeg","/images/sciences/chemistry/julian-2.jpg"],
  "/images/sciences/environmental science & justice/bullard": ["/images/sciences/environmental science & justice/bullard-1.jpg","/images/sciences/environmental science & justice/bullard-2.jpeg"],
  "/images/sciences/environmental science & justice/h-johnson": ["/images/sciences/environmental science & justice/h-johnson-1.webp","/images/sciences/environmental science & justice/h-johnson-2.webp"],
  "/images/sciences/environmental science & justice/jones": ["/images/sciences/environmental science & justice/jones-1.jpg","/images/sciences/environmental science & justice/jones-2.webp"],
  "/images/sciences/environmental science & justice/maathai": ["/images/sciences/environmental science & justice/maathai-1.webp","/images/sciences/environmental science & justice/maathai-2.jpg"],
  "/images/sciences/physics/branson": ["/images/sciences/physics/branson-1.jpg","/images/sciences/physics/branson-2.jpeg"],
  "/images/sciences/physics/gates": ["/images/sciences/physics/gates-1.jpeg","/images/sciences/physics/gates-2.jpg"],
  "/images/sciences/physics/mcnair": ["/images/sciences/physics/mcnair-1.jpg","/images/sciences/physics/mcnair-2.jpg"],
  "/images/sciences/physics/s-jackson": ["/images/sciences/physics/s-jackson-1.jpg","/images/sciences/physics/s-jackson-2.jpg"],
  "/images/technology/computer science/abebe": ["/images/technology/computer science/abebe-1.jpeg","/images/technology/computer science/abebe-2.png"],
  "/images/technology/computer science/emeagwali": ["/images/technology/computer science/emeagwali-1.jpeg","/images/technology/computer science/emeagwali-2.webp"],
  "/images/technology/computer science/gebru": ["/images/technology/computer science/gebru-1.jpg","/images/technology/computer science/gebru-2.webp"],
  "/images/technology/computer science/howard": ["/images/technology/computer science/howard-1.jpeg","/images/technology/computer science/howard-2.jpg"],
  "/images/technology/electrical engineering/latimer": ["/images/technology/electrical engineering/latimer-1.jpeg","/images/technology/electrical engineering/latimer-2.jpeg"],
  "/images/technology/electrical engineering/m-jackson": ["/images/technology/electrical engineering/m-jackson-1.jpg","/images/technology/electrical engineering/m-jackson-2.webp"],
  "/images/technology/electrical engineering/mccoy": ["/images/technology/electrical engineering/mccoy-1.jpg","/images/technology/electrical engineering/mccoy-2.jpeg"],
  "/images/technology/electrical engineering/woods": ["/images/technology/electrical engineering/woods-1.jpg","/images/technology/electrical engineering/woods-2.jpg"],
  "/images/technology/inventors/bath": ["/images/technology/inventors/bath-1.jpeg","/images/technology/inventors/bath-2.jpg"],
  "/images/technology/inventors/morgan": ["/images/technology/inventors/morgan-1.webp","/images/technology/inventors/morgan-2.jpg"],
  "/images/technology/inventors/thomas": ["/images/technology/inventors/thomas-1.jpg","/images/technology/inventors/thomas-2.jpg"],
  "/images/technology/inventors/walker": ["/images/technology/inventors/walker-1.jpg","/images/technology/inventors/walker-2.webp"],
  "/images/technology/software engineering/bryant": ["/images/technology/software engineering/bryant-1.jpeg","/images/technology/software engineering/bryant-2.jpg"],
  "/images/technology/software engineering/clay": ["/images/technology/software engineering/clay-1.jpeg","/images/technology/software engineering/clay-2.webp"],
  "/images/technology/software engineering/ellis": ["/images/technology/software engineering/ellis-1.jpeg","/images/technology/software engineering/ellis-2.jpeg"],
  "/images/technology/software engineering/lawson": ["/images/technology/software engineering/lawson-1.jpg","/images/technology/software engineering/lawson-2.webp"],
};
